# Generated by Django 3.1.2 on 2020-10-30 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemilu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='absen',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='kelas',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pararel',
            field=models.IntegerField(null=True),
        ),
    ]
