# Generated by Django 3.1.2 on 2020-11-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemilu', '0002_auto_20201030_0453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pilih',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilihan', models.CharField(max_length=50, verbose_name='Pilihan')),
            ],
        ),
    ]
