# Generated by Django 3.1.2 on 2020-11-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemilu', '0003_pilih'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilih',
            name='pilihan',
            field=models.CharField(max_length=50, verbose_name='token'),
        ),
    ]
