# Generated by Django 3.1.2 on 2020-11-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemilu', '0004_auto_20201106_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilih',
            name='token',
            field=models.CharField(max_length=50, null=True, verbose_name='token'),
        ),
        migrations.AlterField(
            model_name='pilih',
            name='pilihan',
            field=models.CharField(max_length=50, verbose_name='Pilihan'),
        ),
    ]
